# Generated by Django 5.1.4 on 2025-01-07 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название ингредиента', max_length=128, unique=True, verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Укажите единицы измерения', max_length=64, verbose_name='Единицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(default=False, help_text='Отметьте рецепт в избранное', verbose_name='Находится ли в избранном')),
                ('is_in_shopping_cart', models.BooleanField(default=False, help_text='Отложите рецепт в корзину', verbose_name='Находится ли в корзине')),
                ('name', models.CharField(help_text='Укажите название рецепта', max_length=256, verbose_name='Название рецепта')),
                ('image', models.ImageField(default=None, help_text='Картинка, закодированная в формате Base64.', null=True, upload_to='', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Укажите описание рецепта', verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(help_text='Укажите время приготовления, от 1 мин', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (в минутах)')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Укажите кол-во ингредиента', verbose_name='Кол-во ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент - рецепта',
                'verbose_name_plural': 'Ингредиент - рецепта',
                'ordering': ('recipe',),
            },
        ),
    ]
